In [36]:
from collections import defaultdict
import numpy as np

counter = 0
tmp = []
data = defaultdict(list)


for line in open("data.txt").readlines():
    if line == "\n":
        tmp = [np.array(list(map(int,x))) for x in tmp[1:]]
        data[counter] = tmp
        counter += 1
        tmp = []
    else:
        tmp.append(line.strip().split(","))


print(len(data))


25


# Part 1

In [2]:
import numpy as np
from numpy.linalg import inv

rotations = [
    np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]]),
    np.array([[0, 0, 1], [0, 1, 0], [-1, 0, 0]]),
    np.array([[-1, 0, 0], [0, 1, 0], [0, 0, -1]]),
    np.array([[0, 0, -1], [0, 1, 0], [1, 0, 0]]),
    np.array([[0, -1, 0], [1, 0, 0], [0, 0, 1]]),
    np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]]),
    np.array([[0, 1, 0], [1, 0, 0], [0, 0, -1]]),
    np.array([[0, 0, -1], [1, 0, 0], [0, -1, 0]]),
    np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]]),
    np.array([[0, 0, 1], [-1, 0, 0], [0, -1, 0]]),
    np.array([[0, -1, 0], [-1, 0, 0], [0, 0, -1]]),
    np.array([[0, 0, -1], [-1, 0, 0], [0, 1, 0]]),
    np.array([[1, 0, 0], [0, 0, -1], [0, 1, 0]]),
    np.array([[0, 1, 0], [0, 0, -1], [-1, 0, 0]]),
    np.array([[-1, 0, 0], [0, 0, -1], [0, -1, 0]]),
    np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]]),
    np.array([[1, 0, 0], [0, -1, 0], [0, 0, -1]]),
    np.array([[0, 0, -1], [0, -1, 0], [-1, 0, 0]]),
    np.array([[-1, 0, 0], [0, -1, 0], [0, 0, 1]]),
    np.array([[0, 0, 1], [0, -1, 0], [1, 0, 0]]),
    np.array([[1, 0, 0], [0, 0, 1], [0, -1, 0]]),
    np.array([[0, -1, 0], [0, 0, 1], [-1, 0, 0]]),
    np.array([[-1, 0, 0], [0, 0, 1], [0, 1, 0]]),
    np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]]),
    ]

inv_rotations = [inv(x) for x in rotations]

def rotate(matrix):
    '''Returns all 24 rotations of a set of coordinates.'''
    return [np.transpose(np.matmul(x, np.transpose(matrix))) for x in rotations]


In [40]:
rotate(np.array([[-1,-1,1], [-2,-2,2], [-3,-3,3], [-2,-3,1], [5,6,-4], [8,0,7]]))

[array([[-1, -1,  1],
        [-2, -2,  2],
        [-3, -3,  3],
        [-2, -3,  1],
        [ 5,  6, -4],
        [ 8,  0,  7]]),
 array([[ 1, -1,  1],
        [ 2, -2,  2],
        [ 3, -3,  3],
        [ 1, -3,  2],
        [-4,  6, -5],
        [ 7,  0, -8]]),
 array([[ 1, -1, -1],
        [ 2, -2, -2],
        [ 3, -3, -3],
        [ 2, -3, -1],
        [-5,  6,  4],
        [-8,  0, -7]]),
 array([[-1, -1, -1],
        [-2, -2, -2],
        [-3, -3, -3],
        [-1, -3, -2],
        [ 4,  6,  5],
        [-7,  0,  8]]),
 array([[ 1, -1,  1],
        [ 2, -2,  2],
        [ 3, -3,  3],
        [ 3, -2,  1],
        [-6,  5, -4],
        [ 0,  8,  7]]),
 array([[ 1, -1, -1],
        [ 2, -2, -2],
        [ 3, -3, -3],
        [ 1, -2, -3],
        [-4,  5,  6],
        [ 7,  8,  0]]),
 array([[-1, -1, -1],
        [-2, -2, -2],
        [-3, -3, -3],
        [-3, -2, -1],
        [ 6,  5,  4],
        [ 0,  8, -7]]),
 array([[-1, -1,  1],
        [-2, -2,  2],
        [-3, -3,  

In [3]:
def is_pair(a1, a2):
    '''Check whether two scanners have at least 12 beacons in common. If they do, they are a pair.
    It also returns the respective beacon pair indexes (scanner1, scanner2).
    It also returns the relative position shift of scanner 2 from scanner 1.
    This already assumes the orientation of the two scanners are the same.'''
    deltas = []
    deltas_dic = defaultdict(list)
    
    for i in range(len(a1)): # For each beacon in scanner 1,
        for j in range(len(a2)): # find the distance to each beacon in scanner 2.
            deltas_dic[(i,j)] = list(a1[i]-a2[j]) # Add the distance of each beacon pair to a dictionary.
            deltas.append(list(a1[i]-a2[j])) # Add the distance to a list.
    
    
    count = defaultdict(int)
    for dist in deltas:
        count[str(dist)] += 1 # Summing up the counts of each distance. Need to do str(dist) for hashable.
    
    
    if count[max(count, key=count.get)] >= 12: # If more than 12 distances are the same, then they are a pair, and can be used to map out the area.
        return True, [k for k,v in deltas_dic.items() if str(v)==max(count, key=count.get)], max(count, key=count.get)  # Add the common (beacon1, beacon2) pair indexes.
    else:
        return False

In [5]:
a1 = np.array([[1,2,3],[2,3,4]])
a2 = np.array([[3,4,5],[4,5,6]])
is_pair(a1,a2)

False

In [6]:
from math import ceil
import ast
def get_pairs(dictionary):
    '''Get all the scanner pairs by fixing a scanner, and going through each other scanner and rotating
    them to find whether they are a pair. Also returns the rotation number and relative position
    of scanner2 from scanner1 for pairs = (scanner1, scanner2).
    
    Returns (pairs, rotation number for pairs, and relative positions)
    
    Function can also provide the common beacons, but is not necessary.'''
    
    pairs = []
    relative_positions = []
    #common_beacons = defaultdict(list)
    rotation_num = []
    
    n_scanners = len(dictionary)
    
    for scanner in range(ceil(n_scanners)):
        for possible_pair in range(n_scanners):
            if scanner != possible_pair: # Make sure it's not the same scanner
                rotations = rotate(dictionary[possible_pair])
                for rotation_index in range(len(rotations)): # Finding the correct orientation of the possible pair.
                    if (is_pair(dictionary[scanner], rotations[rotation_index])) and ((possible_pair, scanner) not in pairs): # Add pairs, and also not double count.
                        pairs.append((scanner, possible_pair))
                        rotation_num.append(rotation_index)
                        relative_positions.append(is_pair(dictionary[scanner], rotations[rotation_index])[2])
                        #common_beacons[(scanner, possible_pair)] = is_pair(dictionary[scanner], rotations[rotation_index])[1]
    return pairs, rotation_num, [np.array(ast.literal_eval(x)) for x in relative_positions]#,  common_beacons

In [7]:
get_pairs(data)


([(0, 1), (0, 7), (0, 16), (1, 17), (1, 19), (1, 23), (2, 7), (2, 11), (2, 12), (2, 15), (3, 8), (3, 9), (3, 16), (4, 10), (4, 18), (5, 7), (6, 19), (6, 21), (7, 22), (8, 20), (9, 14), (9, 17), (10, 13), (11, 20), (11, 22), (13, 19), (16, 17), (16, 22), (18, 24)], [15, 21, 22, 21, 3, 20, 18, 6, 14, 10, 17, 12, 5, 6, 2, 11, 20, 22, 12, 22, 19, 16, 10, 5, 9, 8, 19, 11, 21], [array([ -28,   54, 1186]), array([    4,   -48, -1271]), array([  20, 1153,   29]), array([   23,   -74, -1126]), array([ -99, 1134,  -49]), array([1247,   92,    6]), array([   27, -1243,  -146]), array([ -21, -159, 1111]), array([-1186,   -37,   -40]), array([   63,  -118, -1257]), array([  -92, -1160,    49]), array([ -65,   20, 1176]), array([-1330,   -10,   135]), array([ -84,  -59, 1354]), array([-1161,    65,   -40]), array([   49,   -22, -1310]), array([ -22,   72, 1252]), array([-1119,   -19,    79]), array([  48,   97, 1162]), array([1186,  -74,  -88]), array([   91,    -6, -1307]), array([-1238,   139,    

In [19]:
def orient(dictionary):
    '''The transformation required for every scanner to be the same as scanner 0.
    Returns the initial dictionary with all coordinates in the correct orientation.'''
    orient_transform = defaultdict(int)
    not_oriented = list(range(1,len(dictionary)))
    
    pair_info = get_pairs(dictionary)
    
    
    # Initial conditions (Scanner pairs with 0)
    orient_transform[0] = rotations[0]
    for i in range(len(get_pairs(dictionary)[0])):
        if pair_info[0][i][0] == 0:
            not_oriented.remove(pair_info[0][i][1])
            orient_transform[pair_info[0][i][1]] = rotations[pair_info[1][i]]
    
    
    while len(not_oriented) != 0:
         for scanner in not_oriented:
            for i in range(len(pair_info[0])):
                if (scanner == pair_info[0][i][1]) and (pair_info[0][i][0] in orient_transform):
                    orient_transform[scanner] = np.matmul(orient_transform[pair_info[0][i][0]], rotations[pair_info[1][i]])
                    not_oriented.remove(scanner)
                    break
                elif (scanner == pair_info[0][i][0]) and (pair_info[0][i][1] in orient_transform):
                    orient_transform[scanner] = np.matmul(orient_transform[pair_info[0][i][1]], inv_rotations[pair_info[1][i]])
                    not_oriented.remove(scanner)
                    break

     
    oriented = defaultdict(int)
    for i in range(len(dictionary)):
        oriented[i] = [np.matmul(orient_transform[i], beacon) for beacon in dictionary[i]]
    
    return oriented

In [32]:
orient(data)

defaultdict(int,
            {0: [array([ 602,  365, -604]),
              array([ 309, -819, -775]),
              array([-589,  731, -551]),
              array([-803,  817,  548]),
              array([ 325, -731,  774]),
              array([-855, -664,  304]),
              array([-91,  96, -88]),
              array([ 47, -34,  29]),
              array([ 692,  405, -767]),
              array([513, 535, 660]),
              array([ 340, -633, -836]),
              array([399, 500, 577]),
              array([-805,  780,  754]),
              array([-594,  682, -384]),
              array([-814,  882,  768]),
              array([ 316, -768, -918]),
              array([-747, -756,  401]),
              array([-763, -608,  329]),
              array([-842, -465, -620]),
              array([ 382, -782,  771]),
              array([370, 550, 692]),
              array([ 413, -882,  725]),
              array([ 572,  506, -721]),
              array([-647, -437, -631]),
           

In [20]:
def shift(dictionary):
    '''Shifting (CORRECTLY oriented) scanners (output from orient() function) 
    such that the origin is the same as scanner 0. Returns the relative 
    position of each scanner to scanner 0.'''
    
    dictionary = orient(dictionary)
    
    shift_transform = defaultdict(int)
    not_shifted = list(range(1,len(dictionary)))
    
    pair_info = get_pairs(dictionary)
    
    # Initial conditions (Scanners who are 1 shift away from scanner 0)
    shift_transform[0] = np.zeros((3))

    for i in range(len(get_pairs(dictionary)[0])):
        if pair_info[0][i][0] == 0:
            not_shifted.remove(pair_info[0][i][1])
            shift_transform[pair_info[0][i][1]] = pair_info[2][i]
            
            
    while len(not_shifted) != 0:
         for scanner in not_shifted:
            for i in range(len(pair_info[0])):
                if (scanner == pair_info[0][i][1]) and (pair_info[0][i][0] in shift_transform):
                    shift_transform[scanner] = np.add(shift_transform[pair_info[0][i][0]], pair_info[2][i])
                    not_shifted.remove(scanner)
                    break
                elif (scanner == pair_info[0][i][0]) and (pair_info[0][i][1] in shift_transform):
                    shift_transform[scanner] = np.subtract(shift_transform[pair_info[0][i][1]], pair_info[2][i])
                    not_shifted.remove(scanner)
                    break
    
    
    
    
    return shift_transform

In [31]:
shift(data)

defaultdict(int,
            {0: array([0., 0., 0.]),
             1: array([ -28,   54, 1186]),
             7: array([    4,   -48, -1271]),
             16: array([  20, 1153,   29]),
             2: array([ 1247.,    98., -1298.]),
             5: array([-1.306e+03,  1.000e+00, -1.249e+03]),
             11: array([ 1088.,  1209., -1319.]),
             15: array([ 1129., -1159., -1235.]),
             19: array([-1162,   103,  1087]),
             22: array([  -93,  1114, -1319]),
             3: array([  10., 2483., -106.]),
             6: array([-2414.,    81.,  1159.]),
             9: array([ -10., 2418., 1070.]),
             12: array([ 1210.,    58., -2484.]),
             14: array([-1317.,  2509.,  1064.]),
             20: array([ 1096.,  2479., -1243.]),
             23: array([-120,   48, 2433]),
             8: array([1170., 2391.,  -57.]),
             13: array([-1197., -1276.,  1092.]),
             21: array([-2335.,  1200.,  1178.]),
             10: array([-126

In [38]:
def unique(dictionary):
    '''Takes in a data set. Calls the orient function to orient the data set.
    After the data set is oriented, call the shift function to get the shift
    transformation matrix. Apply that transformation matrix to the respective
    scanners. Returns the number of unique beacons 
    '''
    oriented_dictionary = orient(dictionary)
    shift_transform = shift(dictionary)
    beacons = set()
    for scanner in range(len(dictionary)):
        for beacon in range(len(dictionary[scanner])):
            beacon = np.add(shift_transform[scanner], oriented_dictionary[scanner][beacon])
            beacon = [int(x) for x in beacon]
            beacons.add(str(beacon))
    
    return len(beacons)

In [35]:
unique(data)

315

# Part 2

In [39]:
scanners = shift(data)

In [47]:
def manhattan(scanners):
    max_dist = 0
    for scanner in range(len(scanners)):
        for pair in range(len(scanners)):
            dist = sum([abs(x) for x in scanners[scanner]-scanners[pair]])
            if dist > max_dist:
                max_dist = dist
                
    return int(max_dist)

In [48]:
manhattan(scanners)

13192

# Test/Working out

In [20]:
from collections import defaultdict

counter = 0
tmp = []
data = defaultdict(list)


for line in open("test.txt").readlines():
    if line == "\n":
        tmp = [np.array(list(map(int,x))) for x in tmp[1:]]
        data[counter] = tmp
        counter += 1
        tmp = []
    else:
        tmp.append(line.strip().split(","))
        
print((data))

defaultdict(<class 'list'>, {0: [array([ 404, -588, -901]), array([ 528, -643,  409]), array([-838,  591,  734]), array([ 390, -675, -793]), array([-537, -823, -458]), array([-485, -357,  347]), array([-345, -311,  381]), array([-661, -816, -575]), array([-876,  649,  763]), array([-618, -824, -621]), array([ 553,  345, -567]), array([474, 580, 667]), array([-447, -329,  318]), array([-584,  868, -557]), array([ 544, -627, -890]), array([ 564,  392, -477]), array([455, 729, 728]), array([-892,  524,  684]), array([-689,  845, -530]), array([ 423, -701,  434]), array([  7, -33, -71]), array([ 630,  319, -379]), array([443, 580, 662]), array([-789,  900, -551]), array([ 459, -707,  401])], 1: [array([686, 422, 578]), array([605, 423, 415]), array([ 515,  917, -361]), array([-336,  658,  858]), array([ 95, 138,  22]), array([-476,  619,  847]), array([-340, -569, -846]), array([ 567, -361,  727]), array([-460,  603, -452]), array([ 669, -402,  600]), array([729, 430, 532]), array([-500, -

In [100]:
print(test)
print(test[2][0] + test[2][2])
test[2][0] + test[2][2] - test[2][3]

([(0, 1), (1, 3), (1, 4), (2, 4)], [0, 0, 0, 0], [array([   68, -1246,   -43]), array([ -160, -1134,    23]), array([ -88,  113, 1104]), array([-1125.,    72.,  -168.])], defaultdict(<class 'list'>, {(0, 1): [(0, 3), (1, 8), (3, 12), (4, 1), (5, 24), (6, 18), (7, 10), (9, 0), (12, 2), (14, 5), (19, 15), (24, 19)], (1, 3): [(6, 2), (7, 13), (9, 20), (11, 3), (13, 6), (14, 0), (16, 11), (17, 5), (20, 17), (21, 12), (22, 21), (23, 24)], (1, 4): [(2, 4), (6, 11), (8, 24), (13, 1), (15, 18), (16, 15), (18, 17), (19, 5), (21, 13), (22, 12), (23, 16), (24, 3)], (2, 4): [(0, 14), (1, 18), (7, 23), (8, 22), (11, 11), (12, 19), (13, 6), (16, 1), (19, 5), (20, 7), (23, 13), (25, 24)]}))
[  -20 -1133  1061]


array([ 1105., -1205.,  1229.])